// <auto-generated />
using Mi_Primer_API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mi_Primer_API.Migrations
{
    [DbContext(typeof(Tiendas2Context))]
    [Migration("20210303012930_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Mi_Primer_API.Controllers.Tienda", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("ubicacion")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Tiendas");
                });
#pragma warning restore 612, 618
        }
    }
}
